### ISSUE TITLE
无法播放发球情况的录像

### ISSUE THREAD

**Issue by planetarianPKU** [chbpku/pingpong.sessdsa#10]
由于开局发球serve不属于回合内，所以不予记录中间过程，因此录像回放只会回放从球到达对面底线开始，到出界后几秒的画面，未展现中间触壁次数不符合要求的画面。
如下为一次发球失败实例：位置设在左上角，速度为3000
DIM:(-900000, 900000, 0, 1000000)
TMAX:800000
tick_step:1800
West:T_idiot
East:T_idiot
tick_total:0
winner:East
reason:invalid_bounce
log:
tick:0
side:
  life:100000
  pos:<900000,500000>
  action:
    bat:0
    acc:0
    run:0
op_side:
  life:100000
  pos:<-900000,500000>
  action:
    bat:0
    acc:0
    run:0
ball:
  pos:<-900000,1000000>
  velocity:<1000,3000>

tick:0
side:
  life:100000
  pos:<900000,500000>
  action:
    bat:0
    acc:0
    run:0
op_side:
  life:100000
  pos:<-900000,500000>
  action:
    bat:0
    acc:0
    run:0
ball:
  pos:<900000,400000>
  velocity:<1000,3000>
我们可以看出并未记录第一次发球过程
具体原因可能是GUI的球移动原理？（存疑）

**Comment by planetarianPKU** [comment]
原因可能是show.py的原理实现，无法读取失败发球的数据

**Comment by chbpku** [comment]
已经解决了吗？ @HDTTclear

**Comment by pkuzhd** [comment]
@HDTTclear 新的pr里已经修复了自杀发球的显示问题，你试一下

**Comment by planetarianPKU** [comment]
确实已解决，感激不尽！点个赞
