### ISSUE TITLE
关于对serve，play函数的返回值的取整

### ISSUE THREAD

**Issue by zzy546** [chbpku/pingpong.sessdsa#11]
bat_distance = sign(self.action.bat) * min(abs(self.action.bat), self.get_velocity() * tick_step)
        self.pos.y += bat_distance
以及
        pos_y, velocity_y = player.serve(player.datastore)  # 只提供y方向的位置和速度
是否有必要在Table.py中对参赛的函数的返回值取整，防止bug函数返回浮点数。

**Comment by chbpku** [comment]
已通过设置action.normalize方法来对距离和速度值设置为整数。
