### ISSUE TITLE
关于旋转球道具影响游戏平衡的反馈

### ISSUE THREAD

**Issue by RibomBalt** [chbpku/pingpong.sessdsa#16]
![_20170520204201](https://cloud.githubusercontent.com/assets/26453381/26275881/9e2ed44a-3d9d-11e7-8f28-b88d3496faf1.png)
老师我之前汇报过一次的……这个过于影响游戏平衡：
```
CARD_SPIN = 'SP'  # 旋转球：用于抵消被用道具方施加在球拍上的加速，使之正常反弹回来；param=0，增加的速度乘以parm
CARD_SPIN_PARAM = 0
```

个人感觉这个属于设计漏洞，拿到旋转球的玩家拥有必胜策略，而旋转球的出现是随机的，独立于代码水平之外的，私以为用这个来决定胜负和掷骰子决定胜负没有什么本质区别。

因此我建议，删除这个道具，或者削弱这个道具的功能，或者限定这个道具只能在残局（比如双方生命值均小于30%，有大量范围无法运动到达）时出现

**Comment by chbpku** [comment]
那么，如果把旋转球的作用改成：将对方施加在球拍上的加速度减半。
这个如何？

**Comment by chbpku** [comment]
@RibomBalt

**Comment by Albert-Libra** [comment]
这招是有死角的吧。把球打到对方的角落处，让对方在角落处接球，球将会沿对角线运动，这样根据碰撞次数的计算方法，即使对方有旋转球也无法做到一击必胜了

**Comment by RibomBalt** [comment]
@LuoZheKai 角落处还可以构造出那种弹两次的必杀情况。

**Comment by RibomBalt** [comment]
@chbpku 感觉可以，不过1/2的系数还需要调整。这个会对策略有一定制约。
另外能否知道对方用了道具？如果可以知道，我有个建议，系数用1/3到2/3间的一个随机数，既保证了随机性，又可以进行一定的控制。

**Comment by chbpku** [comment]
@RibomBalt 能知道对方用了道具。随机数的意思是用道具的一方不能预知效果？但是被用道具的一方能知道这个数？

**Comment by chbpku** [comment]
如果双方都不知道这个随机数，可能不太合理。

**Comment by chbpku** [comment]
应该说，旋转球的设置，不是为了一招制胜，但它是消耗对方体力的一个有效手段，让对方想达到预定效果击球的话，需要付出更多的体力。这个道具跟变压器类似，但也有区别。

**Comment by RibomBalt** [comment]
@chbpku 
如果双随机不合理，也可以让发球方自主选择参数（调用道具那里加一个参数，可以用\*args，不影响不需要参数的部分）
这样，发球方可以知道参数，参数必须限定在一个合法的范围内，接球方只能知道对方用了道具。
同时为了保证不会一招制胜，我建议，可选择的范围应该保证：接球方可以找到一个**发球角度（与参数无关）**，使得他 __按照这个角度算出的加速值对球加速__，无论选择了什么参数，发出的球都是合法的（符合弹1-2次）。（下文把 __这个加速值的邻域__ 称为**安全区**）。这样，接球方可以选择这个很小的安全区，但会导致发球方向不一定符合自己的利益，并且 __安全区算法对方应该也能算出来__，这一回合可以被道具方 **预判**；也可以不选择安全区，冒被秒杀的风险来制造随机性。
另外参数选择范围也可以和使用道具的一方位置有关，降低调参难度。这样也可以实现（比如给道具一个小函数），没有很大的技术困难。
如果用一种隐晦的方式告诉大家安全区的存在，那我觉得就彻底解决了秒杀的问题，并且也能达到迷惑战局、消耗对方的目的。

【啊……本来想用MarkDown加粗强调的，看来出了点bug】

**Comment by chbpku** [comment]
@RibomBalt 参数合法范围如果是一个相对值的话，在规则复杂性和调试复杂性方面都会加大很多，但由于也还是要考虑到对方有不被秒杀的可能，其实际效果可能跟确定一个固定的加速倍数基本相同。
而如果参数值固定为，比如将对方的加速削弱一半的话，也同样达到了加大对方体力值消耗，干扰其正常策略的目的。

**Comment by RibomBalt** [comment]
@chbpku 如果是固定值的话，假如对方不知道你用了道具，那么就比较有可能被秒杀【比如他想擦边打，结果对方用了道具，导致调整的角度不够弹1-2次】。假如知道，那就只剩下多消耗对方体力的目的了，不能增加战场的随机性。两害相权取其轻，我觉得还是让对方知道你用了道具比较好。或者可以这样，让对方知道你用了道具，但是不知道你用了哪个道具。这样调试难度没有，然后也保证了一定的随机性

**Comment by chbpku** [comment]
对方知道我使用的道具，当然对方也可以在没有危害的前提下选择不对球加速，就没有任何体力损失，相当于逼迫对方更换应对策略。
至于随机性，我希望平台所产生的随机性尽量少，可预测。把随机性的发挥留给双方算法去耍。

**Comment by RibomBalt** [comment]
可以
