### ISSUE TITLE
李逸飞同学的fly函数将DIM[2]默认为0，我认为这不妥

### ISSUE THREAD

**Issue by alleriawr9** [chbpku/pingpong.sessdsa#18]
DIM[2]（y方向位置下限）与生命值，消耗系数等数据一同在table.py开头给出，应当认为这是一个能修改的参数。其余部分代码也确实没有将其默认为0，而是使用DIM得到范围。

**Comment by chbpku** [comment]
DIM[3]-DIM[2]?

**Comment by RibomBalt** [comment]
@alleriawr9 感觉这种类型的问题直接发pull request，不用发issue。
感觉的确不妥，虽然DIM[2]改动的可能性十分小。

**Comment by chbpku** [comment]
@liyfpku 是否所有self.extent[3]都要改为(self.extent[3]- self.extent[2])

**Comment by alleriawr9** [comment]
有的self.extent[3]是self.extent[3]-self.extent[2]，有的不是，其实挺麻烦的。。

**Comment by liyfpku** [comment]
的确不妥。但我想你们应该不会动DIM[2]了，所以就没改。因为涉及到反射变换，所以不能单纯的把self.extent[3]改成self.extent[3]-self.extent[2]
如果你们需要修改DIM[2]的话，那我再计算

**Comment by chbpku** [comment]
不动DIM[2]~
