### ISSUE TITLE
最新版show.py无法使用

### ISSUE THREAD

**Issue by planetarianPKU** [chbpku/pingpong.sessdsa#21]
报错
D:\python3.61\python.exe E:/PYhomework/pingpong.sessdsa-master/show.py
Traceback (most recent call last):
  File "E:/PYhomework/pingpong.sessdsa-master/show.py", line 204, in <module>
    main()
  File "E:/PYhomework/pingpong.sessdsa-master/show.py", line 165, in main
    t_passed = clock.tick()*m
TypeError: unsupported operand type(s) for *: 'int' and '_sre.SRE_Match'

Process finished with exit code 1

**Comment by pkuzhd** [comment]
刚才才别的电脑上也遇到了这个情况，删去165行的*m就能解决，或者在165行的上一行加一句m=1的赋值

**Comment by pkuzhd** [comment]
找到问题的原因了，滥用全局变量的后果

**Comment by planetarianPKU** [comment]
删去程序最前的m，在165行之前加一个m即可解决。而且仍可调参

**Comment by pkuzhd** [comment]
最主要的原因是后面的正则表达式中也用了m作为变量名，最好的解决办法是把最开始和165行的m都改一个名字

**Comment by planetarianPKU** [comment]
已解决
顺便赞自动读取

**Comment by chbpku** [comment]
已解决。
