### ISSUE TITLE
关于记录不完全的问题

### ISSUE THREAD

**Issue by pkuzhd** [chbpku/pingpong.sessdsa#3]
假设在tn-1到tn之间因为某种原因游戏结束（时间耗尽，或者迎球方在tn时刻移动造成生命耗尽），不会保存tn时刻的记录，如果是因为生命耗尽引起，就无法知道迎球方的动作了。这种情况下可能tn-1时刻迎球的一方处于劣势，但因为tn时刻迎球方的行动导致胜负逆转，无法在记录上体现出来。
建议对最后一次log进行单独记录。

**Comment by chbpku** [comment]
已加！
