### ISSUE TITLE
现在的pingpong.py如果重复对局，默认是把ds中的数据积存下来？

### ISSUE THREAD

**Issue by RibomBalt** [chbpku/pingpong.sessdsa#31]
我在play里面做了一个累计变量ds['time']，然后每调用一次play就+1，结果发现，多次运行时，这个值从上一次比赛结束的地方开始累加了。
能不能设置成可以选择的呢？

**Comment by chbpku** [comment]
你可以在开局的时候初始化这个time啊，开局的判断是看tick值。
实际上，采用tabledata里面的tick，就不需要你这个time了。

**Comment by RibomBalt** [comment]
明白了，老师可以更新一下FAQ

**Comment by chbpku** [comment]
已更新FAQ
