### ISSUE TITLE
关于迎球和跑位

### ISSUE THREAD

**Issue by pkuzhd** [chbpku/pingpong.sessdsa#4]
迎球和跑位的代价相同，完全可以不跑位，迎球的时候再移动，这样跑位就失去意义了，建议跑位消耗较少的生命值（需要预判），而迎球消耗较多的生命值。

**Comment by chbpku** [comment]
目前的设定，消耗体力值是距离的平方，所以两次跑动比一次跑动，虽然距离相同，但消耗的体力值不同。

**Comment by pkuzhd** [comment]
现有代码中的设定是距离的一次方，加速度的二次方
`self.life -= abs(self.action.bat) / FACTOR_DISTANCE`

`self.life -= abs(self.action.run) / FACTOR_DISTANCE`

`self.life -= (abs(self.action.acc) / FACTOR_SPEED) ** 2`

**Comment by chbpku** [comment]
已改为平方：
`self.life -= int((abs(self.action.bat) / FACTOR_DISTANCE) ** 2)`
并取整：
`self.life -= int((abs(self.action.acc) / FACTOR_SPEED) ** 2)`
