### ISSUE TITLE
道具包提交：马里奥赛车8限定版道具包

### ISSUE THREAD

**Issue by RibomBalt** [chbpku/pingpong.sessdsa#42]
嗯，希望能采纳一部分。
个人感觉变压器、隐身术形容十分贴切……加血包和掉血包也不错……

![default](https://cloud.githubusercontent.com/assets/26453381/26408614/dbf67de2-40d0-11e7-9f53-63aa8b91e364.png)
![default](https://cloud.githubusercontent.com/assets/26453381/26408613/dbf6313e-40d0-11e7-9330-a728addf3aa1.png)
![default](https://cloud.githubusercontent.com/assets/26453381/26408616/dbff0912-40d0-11e7-8d41-8b9ad29d9fda.png)
![default](https://cloud.githubusercontent.com/assets/26453381/26408615/dbf89942-40d0-11e7-895f-5f5d3da48a73.png)
![default](https://cloud.githubusercontent.com/assets/26453381/26408612/dbf563bc-40d0-11e7-8cb8-7c9964e440f9.png)
![default](https://cloud.githubusercontent.com/assets/26453381/26408617/dc2d3008-40d0-11e7-8fa2-f9e209b9cc4f.png)
最后来一个zip文件
[马车8限定主题道具包.zip](https://github.com/chbpku/pingpong.sessdsa/files/1025909/8.zip)

**Comment by RibomBalt** [comment]
哦图片没带标题，从上到下分别是：
掉血
加血
瞬移
旋转
隐身
变压

**Comment by chbpku** [comment]
谢谢！可能需要抽象一些，让大家一眼就能凭直觉看出比较好。
