### ISSUE TITLE
跑位信息的bug

### ISSUE THREAD

**Issue by 1600012423** [chbpku/pingpong.sessdsa#43]
在任何一局对战中，传给play的op_side始终没有对方跑完位后的位置，我认为这不妥，不应该属于信息的不完全。我在击球的时候，确实不应该知道对方上次击球后的跑位，但是我应该知道上上次的对方击球的跑位，这是我在上次击完球之后，应该能够看见的。所以我认为在op_side中需要加入last_run_vector,来表示上上次对方跑位的状况，这个应该是策略的极其重要的一部分：对方的跑位策略。

**Comment by chbpku** [comment]
有的，对方的position加上run_vector很容易计算出跑位结束后的位置。

**Comment by zzy546** [comment]
run_vector不只是方向吗，通过position只能知道跑位加上接球的距离

**Comment by chbpku** [comment]
嗯，对方上上次的跑位状况可以根据其接球位置和体力消耗来综合判断下，虽然不那么精确，但可以限定在一个范围内。
