### ISSUE TITLE
建议：优化目录结构

### ISSUE THREAD

**Issue by RibomBalt** [chbpku/pingpong.sessdsa#46]
这个问题早就应该提出来的，但是现在才比较明显。
建议所有T_*.py代码放在src目录下，所有非.py配置文件放在config目录下，图标文件放在res目录下，记录文件放在log目录下
不然现在的目录结构太乱了，我们也很不好测试。

**Comment by RibomBalt** [comment]
然后目录结构要改的话，对应调用文件的代码也要改

**Comment by chbpku** [comment]
不用目录是为了代码中对各种文件的调用简单来考虑的，毕竟本项目文件很少，应该可以忍受：）
