### ISSUE TITLE
关于道具获取可能与路径经过的先后顺序不一致的问题

### ISSUE THREAD

**Issue by JeffWGL** [chbpku/pingpong.sessdsa#49]
table.py 
第351行：   self.cards中的道具是按照生成的时间顺序存放的

    def deploy_card(self):  # 放置道具到球桌上
        ...
            self.cards.append(Card(card_info[0], card_info[1],
                                   Position(random.randint(CARD_EXTENT[0], CARD_EXTENT[1]),
                                            random.randint(CARD_EXTENT[2], CARD_EXTENT[3]))))
        ...

第147行：  fly函数中检查是否获取道具是按照list_cards顺序检查

    def fly(self, ticks, list_cards):  # 球运动，更新位置，并返回触壁次数和路径经过的道具（元组）
        # 判断card.pos，如果球经过的话，就返回count的同时返回所有经过的道具列表，并从list_cards中移除。
        hit_cards = [card for card in list_cards if self.get_card(card)]

第381行： 调用fly时传入的是self.cards
        count_bounce, hit_cards = self.ball.fly(self.tick_step, self.cards)

第387行： 路径经过的道具比较多的时候，由于有存放数量限制，最终存入的道具可能与遇到的先后顺序不匹配

        # 将击中的道具加入道具箱
        for card in hit_cards:
            op_player.card_box.collect(card)

**Comment by chbpku** [comment]
已修改，按照获取先后次序来排序道具了。
