### ISSUE TITLE
隐身卡的问题

### ISSUE THREAD

**Issue by 1600012423** [chbpku/pingpong.sessdsa#54]
实际上对方的位置完全可以由上回合的自己的位置和击出球的速度算出来，因此隐身道具没有实际用途。

**Comment by planetarianPKU** [comment]
噗哈哈哈哈，真相了
厉害了

**Comment by chbpku** [comment]
隐身是你无法知道对方的跑位情况，这个是没法推算的。 @1600012423

**Comment by 1600012423** [comment]
哦，那这样的话隐身道具作用还是比较小吧。
