### ISSUE TITLE
关于道具出现的时机

### ISSUE THREAD

**Issue by Nithouson** [chbpku/pingpong.sessdsa#57]
根据道具出现的间隔和tickstep的关系，有的道具先手方有机会先抢到，有的道具后手有机会先抢到。
按已有参数，出现了连续4个道具一方有机会先抢，接着连续4个道具另一方有机会先抢的情况。
这似乎并不合适。

**Comment by Nithouson** [comment]
而且我组出现了相同的算法到west抢很多道具，到east几乎不抢的情形。不知其他组是否有类此情况。

**Comment by chbpku** [comment]
现在CARD_FREQ改为了tickstep的5倍，每5趟出现一个道具，这样应该没问题了。
