### ISSUE TITLE
关于取整

### ISSUE THREAD

**Issue by zzy546** [chbpku/pingpong.sessdsa#7]
elif self.velocity.y > 0:  # 向上y+飞
            # y方向的位置，考虑触壁反弹
            bounce_ticks = (self.extent[3] - self.pos.y) / self.velocity.y
            if bounce_ticks >= ticks:  # 没有触壁
                self.pos.y += self.velocity.y * ticks
                return 0
            else:  # 至少1次触壁
                # 计算后续触壁
                ticks -= bounce_ticks
                count, remain = divmod(ticks, ((self.extent[3] - self.extent[2]) / self.velocity.y))
                if count % 2 == 0:  # 偶数，则是速度改变方向
                    self.pos.y = self.extent[3] - remain * self.velocity.y
                    self.velocity.y = -self.velocity.y
                else:  # 奇数，速度方向不变
                    self.pos.y = self.extent[2] + remain * self.velocity.y
                return count + 1
好像bounce_ticks可以取到浮点数，使ticks也取到浮点数，divmod第二个参数也可能是浮点数，所以remain和self.pos.y也会是浮点数。

**Comment by chbpku** [comment]
谢谢！拟用李逸飞同学的新算法替代这段代码，即可解决取整问题：
```
        Y = self.velocity.y * ticks + self.pos.y  # Y是没有墙壁时到达的位置
        if Y % self.extent[3] != 0:  # case1：未在边界
            count = Y // self.extent[3]  # 穿过了多少次墙（可以是负的，最后取绝对值）

            # 两种情形：a） 穿过偶数次墙，这时没有对称变换，速度保持不变。到达的位置就是Y0=Y-self.extent[3]*count
            #           b） 穿过奇数次墙，是一次对称和一次平移的复合，速度反向。先做平移，到达Y0=Y-self.extent[3]*count，再反射，到self.extent[3]-Y0
            # 综合两种情形，奇数时Y0是负的，多一个self.extent[3];偶数时Y0是正的，没有self.extent[3]。综上，ynew=Y0*(-1)^count+(1-(-1)^count)/2*self.extent[3]
            # 因不清楚负数能不能做任意整指数幂，所以用取余来表示奇偶性。

            self.pos.y = (Y - count * self.extent[3]) * (1 - 2 * (count % 2)) + self.extent[3] * (count % 2)
            self.velocity.y = self.velocity.y * ((count + 1) % 2 * 2 - 1)
            return abs(count)
        else:  # case2： 恰好在边界

            # 两种情形：a） 向上穿墙，穿了1 - Y // self.extent[3] 次（代入Y = 0验证）
            #           b） 向下穿墙，穿了 Y // self.extent[3] 次（代入Y = self.extent[3] 验证）
            # 无论怎样，实际位置要么在0，要么在self.extent[3]。直接模( 2 * self.extent[3] )即可。
            # 速度只和count奇偶有关，同上。

            count = (Y // self.extent[3]) if (Y > 0) else (1 - Y // self.extent[3])
            self.pos.y = Y % (2 * self.extent[3])
            self.velocity.y = self.velocity.y * ((count + 1) % 2 * 2 - 1)
            return count
            # ===========END==============
```

**Comment by chbpku** [comment]
closed
