### ISSUE TITLE
关于传参时copy的问题

### ISSUE THREAD

**Issue by yusenz** [chbpku/pingpong.sessdsa#73]
由于现在传参时用的是普通的copy，算法可以对所传对象所引用的对象进行修改（主要是cardbox、cards所引用的card），并且active_card传入时未使用copy，其参数也可以被修改。vector、card由于其字段是值类型因此可以用copy，但字段是引用类型的必须用deepcopy。

**Comment by chbpku** [comment]
为了提高深拷贝效率，自定义了card_copy函数。

**Comment by yusenz** [comment]
active_card也需要copy
